spring.application.name=pagos

# Si quieres que el job se ejecute automáticamente al iniciar:
spring.batch.job.enabled=true

#spring.datasource.url=jdbc:postgresql://qa-server:5432/batchdb
#spring.datasource.username=batch_qa
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:mysql://localhost:3306/pagos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=devuser
spring.datasource.password=Password123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.initialize-schema=never
app.input-file=/data/qa/personas.csv
app.output-file=/data/qa/salida.csv