#QA-PROPERTIES
##BD
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=0.0.0.0)(PORT=4410))(CONNECT_DATA=(SERVICE_NAME=NAME)))
spring.datasource.username=USER
spring.datasource.password=password
##
numero.registros=0
ultima.fecha.procesada.default=date

#Kafka-config
kafka.bootstrap.servers.config=broker1:9092,broker2:9092
kafka.key.serializer.class.config=org.apache.kafka.common.serialization.StringSerializer
kafka.value.serializer.class.config=org.apache.kafka.common.serialization.StringSerializer
kafka.value.serializer.class.config.string=org.apache.kafka.common.serialization.StringSerializer

kafka.security.protocol.config=SSL
kafka.ssl.truststore.location.config=${ENVIROMENT_VAR}/PROJECT/PATH/SSL/clients.truststore.jks
kafka.ssl.truststore.password.config=passwordTrustore
kafka.ssl.keystore.location.config=${ENVIROMENT_VAR}/PROJECT/PATH/SSL/ubsappl02.keystore.jks
kafka.ssl.keystore.password.config=passwordKeystore
kafka.ssl.key.password.config=passwordconfig

kafka.acks.config=all
kafka.retries.config=3
#kafka.compression.type.config=none
kafka.compression.type.config=snappy

#Topicos
kafka.topic.valido=TOPICO_VALIDO
kafka.topic.error=TOPICO_ERROR

spring.application.name=
# Si quieres que el job se ejecute automáticamente al iniciar:
#spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=never
#spring.datasource.url=jdbc:postgresql://qa-server:5432/batchdb
#spring.datasource.username=batch_qa
#spring.datasource.password=${DB_PASSWORD}
#spring.batch.jdbc.initialize-schema=never

spring.datasource.url=jdbc:mysql://localhost:3306/pagos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=devuser
spring.datasource.password=Password123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.batch.jdbc.initialize-schema=always
app.input-file=/data/qa/personas.csv
app.output-file=/data/qa/salida.csv
